#!/bin/bash
mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${MARIADB_TEST_DATABASE}\`;
    GRANT ALL PRIVILEGES ON \`${MARIADB_TEST_DATABASE}\`.* TO '${MARIADB_USER}'@'%';
EOSQL