<?php

declare(strict_types=1);

namespace App\Util;

final class CryptoCurrencies
{
    public const string BTC = 'BTC';
    public const string ETH = 'ETH';
    public const string USDT = 'USDT';
    public const string BNB = 'BNB';
    public const string SOL = 'SOL';
    public const string XRP = 'XRP';
    public const string USDC = 'USDC';
    public const string ADA = 'ADA';
    public const string AVAX = 'AVAX';
    public const string DOGE = 'DOGE';
    public const string DOT = 'DOT';
    public const string TRX = 'TRX';
    public const string LINK = 'LINK';
    public const string MATIC = 'MATIC';
    public const string BCH = 'BCH';
    public const string LTC = 'LTC';
    public const string SHIB = 'SHIB';
    public const string DAI = 'DAI';
    public const string ATOM = 'ATOM';
    public const string ETC = 'ETC';
    public const string XLM = 'XLM';
    public const string XMR = 'XMR';
    public const string OKB = 'OKB';
    public const string CRO = 'CRO';
    public const string FIL = 'FIL';
    public const string VET = 'VET';
    public const string ICP = 'ICP';
    public const string THETA = 'THETA';
    public const string AXS = 'AXS';
    public const string EGLD = 'EGLD';
    public const string MANA = 'MANA';
    public const string NEAR = 'NEAR';
    public const string SAND = 'SAND';
    public const string AAVE = 'AAVE';
    public const string CAKE = 'CAKE';
    public const string GRT = 'GRT';
    public const string KLAY = 'KLAY';
    public const string HBAR = 'HBAR';
    public const string BSV = 'BSV';
    public const string MKR = 'MKR';
    public const string STX = 'STX';
    public const string FLOW = 'FLOW';
    public const string QNT = 'QNT';
    public const string RUNE = 'RUNE';
    public const string ZEC = 'ZEC';
    public const string HNT = 'HNT';
    public const string TFUEL = 'TFUEL';
    public const string ONE = 'ONE';
    public const string ENJ = 'ENJ';
    public const string HOT = 'HOT';
    public const string SUSHI = 'SUSHI';
    public const string CELO = 'CELO';
    public const string CHZ = 'CHZ';
    public const string COMP = 'COMP';
    public const string SNX = 'SNX';
    public const string YFI = 'YFI';
    public const string ZIL = 'ZIL';
    public const string QTUM = 'QTUM';
    public const string BAT = 'BAT';
    public const string BTG = 'BTG';
    public const string DCR = 'DCR';
    public const string RVN = 'RVN';
    public const string WAVES = 'WAVES';
    public const string ICX = 'ICX';
    public const string ONT = 'ONT';
    public const string ZRX = 'ZRX';
    public const string OMG = 'OMG';
    public const string ANKR = 'ANKR';
    public const string ZEN = 'ZEN';
    public const string IOST = 'IOST';
    public const string SC = 'SC';
    public const string DGB = 'DGB';
    public const string XVG = 'XVG';
    public const string BTT = 'BTT';
    public const string BTS = 'BTS';
    public const string NANO = 'NANO';
    public const string LSK = 'LSK';
    public const string TON = 'TON';
    public const string PEPE = 'PEPE';
    public const string ARB = 'ARB';
    public const string OP = 'OP';
    public const string TIA = 'TIA';
    public const string SUI = 'SUI';
    public const string STR = 'STR';
    public const string SEI = 'SEI';
    public const string INJ = 'INJ';
    public const string RNDR = 'RNDR';
    public const string FET = 'FET';
    public const string AGIX = 'AGIX';
    public const string OCEAN = 'OCEAN';
    public const string KAS = 'KAS';
    public const string BEAM = 'BEAM';
    public const string PYTH = 'PYTH';
    public const string JUP = 'JUP';
    public const string BONK = 'BONK';
    public const string FLOKI = 'FLOKI';
    public const string WIF = 'WIF';
    public const string UNI = 'UNI';
    public const string EOS = 'EOS';
    public const string NEO = 'NEO';
    public const string IOTA = 'IOTA';
    public const string DASH = 'DASH';
    public const string VEN = 'VEN';
    public const string XEM = 'XEM';
    public const string ALGO = 'ALGO';
    public const string XTZ = 'XTZ';
    public const string LUNA = 'LUNA';
    public const string NXT = 'NXT';
    public const string HEX = 'HEX';
    public const string FTT = 'FTT';
    public const string MIOTA = 'MIOTA';

    /**
     * 0: Name
     * 1: Icon Path (relative to public directory).
     *
     * @var array<string, array{0: string, 1: string}>
     */
    public static array $list = [
        self::BTC => ['Bitcoin', 'icons/crypto/btc.svg'],
        self::ETH => ['Ethereum', 'icons/crypto/eth.svg'],
        self::USDT => ['Tether', 'icons/crypto/usdt.svg'],
        self::BNB => ['BNB', 'icons/crypto/bnb.svg'],
        self::SOL => ['Solana', 'icons/crypto/sol.svg'],
        self::XRP => ['XRP', 'icons/crypto/xrp.svg'],
        self::USDC => ['USD Coin', 'icons/crypto/usdc.svg'],
        self::ADA => ['Cardano', 'icons/crypto/ada.svg'],
        self::AVAX => ['Avalanche', 'icons/crypto/avax.svg'],
        self::DOGE => ['Dogecoin', 'icons/crypto/doge.svg'],
        self::DOT => ['Polkadot', 'icons/crypto/dot.svg'],
        self::TRX => ['TRON', 'icons/crypto/trx.svg'],
        self::LINK => ['Chainlink', 'icons/crypto/link.svg'],
        self::MATIC => ['Polygon', 'icons/crypto/matic.svg'],
        self::BCH => ['Bitcoin Cash', 'icons/crypto/bch.svg'],
        self::LTC => ['Litecoin', 'icons/crypto/ltc.svg'],
        self::SHIB => ['Shiba Inu', 'icons/crypto/shib.svg'],
        self::DAI => ['Dai', 'icons/crypto/dai.svg'],
        self::ATOM => ['Cosmos', 'icons/crypto/atom.svg'],
        self::ETC => ['Ethereum Classic', 'icons/crypto/etc.svg'],
        self::XLM => ['Stellar', 'icons/crypto/xlm.svg'],
        self::XMR => ['Monero', 'icons/crypto/xmr.svg'],
        self::OKB => ['OKB', 'icons/crypto/okb.png'],
        self::CRO => ['Cronos', 'icons/crypto/cro.png'],
        self::FIL => ['Filecoin', 'icons/crypto/fil.svg'],
        self::VET => ['VeChain', 'icons/crypto/vet.svg'],
        self::ICP => ['Internet Computer', 'icons/crypto/icp.svg'],
        self::THETA => ['Theta Network', 'icons/crypto/theta.svg'],
        self::AXS => ['Axie Infinity', 'icons/crypto/axs.png'],
        self::EGLD => ['MultiversX', 'icons/crypto/egld.png'],
        self::MANA => ['Decentraland', 'icons/crypto/mana.svg'],
        self::NEAR => ['NEAR Protocol', 'icons/crypto/near.png'],
        self::SAND => ['The Sandbox', 'icons/crypto/sand.svg'],
        self::AAVE => ['Aave', 'icons/crypto/aave.svg'],
        self::CAKE => ['PancakeSwap', 'icons/crypto/cake.png'],
        self::GRT => ['The Graph', 'icons/crypto/grt.svg'],
        self::KLAY => ['Klaytn', 'icons/crypto/klay.png'],
        self::HBAR => ['Hedera', 'icons/crypto/hbar.png'],
        self::BSV => ['Bitcoin SV', 'icons/crypto/bsv.svg'],
        self::MKR => ['Maker', 'icons/crypto/mkr.svg'],
        self::STX => ['Stacks', 'icons/crypto/stx.svg'],
        self::FLOW => ['Flow', 'icons/crypto/flow.png'],
        self::QNT => ['Quant', 'icons/crypto/qnt.svg'],
        self::RUNE => ['THORChain', 'icons/crypto/rune.png'],
        self::ZEC => ['Zcash', 'icons/crypto/zec.svg'],
        self::HNT => ['Helium', 'icons/crypto/hnt.png'],
        self::TFUEL => ['Theta Fuel', 'icons/crypto/tfuel.png'],
        self::ONE => ['Harmony', 'icons/crypto/one.svg'],
        self::ENJ => ['Enjin Coin', 'icons/crypto/enj.svg'],
        self::HOT => ['Holo', 'icons/crypto/hot.svg'],
        self::SUSHI => ['SushiSwap', 'icons/crypto/sushi.svg'],
        self::CELO => ['Celo', 'icons/crypto/celo.png'],
        self::CHZ => ['Chiliz', 'icons/crypto/chz.svg'],
        self::COMP => ['Compound', 'icons/crypto/comp.svg'],
        self::SNX => ['Synthetix', 'icons/crypto/snx.svg'],
        self::YFI => ['yearn.finance', 'icons/crypto/yfi.svg'],
        self::ZIL => ['Zilliqa', 'icons/crypto/zil.svg'],
        self::QTUM => ['Qtum', 'icons/crypto/qtum.svg'],
        self::BAT => ['Basic Attention Token', 'icons/crypto/bat.svg'],
        self::BTG => ['Bitcoin Gold', 'icons/crypto/btg.svg'],
        self::DCR => ['Decred', 'icons/crypto/dcr.svg'],
        self::RVN => ['Ravencoin', 'icons/crypto/rvn.svg'],
        self::WAVES => ['Waves', 'icons/crypto/waves.svg'],
        self::ICX => ['ICON', 'icons/crypto/icx.svg'],
        self::ONT => ['Ontology', 'icons/crypto/ont.svg'],
        self::ZRX => ['0x', 'icons/crypto/zrx.svg'],
        self::OMG => ['OMG Network', 'icons/crypto/omg.svg'],
        self::ANKR => ['Ankr', 'icons/crypto/ankr.svg'],
        self::ZEN => ['Horizen', 'icons/crypto/zen.svg'],
        self::IOST => ['IOST', 'icons/crypto/iost.svg'],
        self::SC => ['Siacoin', 'icons/crypto/sc.svg'],
        self::DGB => ['DigiByte', 'icons/crypto/dgb.svg'],
        self::XVG => ['Verge', 'icons/crypto/xvg.svg'],
        self::BTT => ['BitTorrent', 'icons/crypto/btt.svg'],
        self::BTS => ['BitShares', 'icons/crypto/bts.svg'],
        self::NANO => ['Nano', 'icons/crypto/nano.svg'],
        self::LSK => ['Lisk', 'icons/crypto/lsk.svg'],
        self::TON => ['Toncoin', 'icons/crypto/ton.png'],
        self::PEPE => ['Pepe', 'icons/crypto/pepe.png'],
        self::ARB => ['Arbitrum', 'icons/crypto/arb.png'],
        self::OP => ['Optimism', 'icons/crypto/op.png'],
        self::TIA => ['Celestia', 'icons/crypto/tia.png'],
        self::SUI => ['Sui', 'icons/crypto/sui.png'],
        self::STR => ['Stellar (old)', 'icons/crypto/str.svg'],
        self::SEI => ['Sei', 'icons/crypto/sei.png'],
        self::INJ => ['Injective', 'icons/crypto/inj.png'],
        self::RNDR => ['Render', 'icons/crypto/rndr.png'],
        self::FET => ['Fetch.ai', 'icons/crypto/fet.png'],
        self::AGIX => ['SingularityNET', 'icons/crypto/agix.png'],
        self::OCEAN => ['Ocean Protocol', 'icons/crypto/ocean.png'],
        self::KAS => ['Kaspa', 'icons/crypto/kas.png'],
        self::BEAM => ['Beam', 'icons/crypto/beam.svg'],
        self::PYTH => ['Pyth Network', 'icons/crypto/pyth.png'],
        self::JUP => ['Jupiter', 'icons/crypto/jup.png'],
        self::BONK => ['Bonk', 'icons/crypto/bonk.png'],
        self::FLOKI => ['Floki', 'icons/crypto/floki.png'],
        self::WIF => ['dogwifhat', 'icons/crypto/wif.png'],
        self::UNI => ['Uniswap', 'icons/crypto/uni.svg'],
        self::EOS => ['EOS', 'icons/crypto/eos.svg'],
        self::NEO => ['NEO', 'icons/crypto/neo.svg'],
        self::IOTA => ['IOTA', 'icons/crypto/iota.svg'],
        self::DASH => ['Dash', 'icons/crypto/dash.svg'],
        self::VEN => ['VeChain (old)', 'icons/crypto/ven.svg'],
        self::XEM => ['NEM', 'icons/crypto/xem.svg'],
        self::ALGO => ['Algorand', 'icons/crypto/algo.svg'],
        self::XTZ => ['Tezos', 'icons/crypto/xtz.svg'],
        self::LUNA => ['Terra', 'icons/crypto/luna.png'],
        self::NXT => ['Nxt', 'icons/crypto/nxt.svg'],
        self::HEX => ['HEX', 'icons/crypto/hex.png'],
        self::FTT => ['FTX Token', 'icons/crypto/ftt.png'],
        self::MIOTA => ['IOTA (MIOTA)', 'icons/crypto/miota.svg'],
    ];
}
