<?php

declare(strict_types=1);

namespace App\Util;

final class Currencies
{
    public const string AED = 'AED';
    public const string AFN = 'AFN';
    public const string ALL = 'ALL';
    public const string AMD = 'AMD';
    public const string ANG = 'ANG';
    public const string AOA = 'AOA';
    public const string ARS = 'ARS';
    public const string AUD = 'AUD';
    public const string AWG = 'AWG';
    public const string AZN = 'AZN';
    public const string BAM = 'BAM';
    public const string BBD = 'BBD';
    public const string BDT = 'BDT';
    public const string BGN = 'BGN';
    public const string BHD = 'BHD';
    public const string BIF = 'BIF';
    public const string BMD = 'BMD';
    public const string BND = 'BND';
    public const string BOB = 'BOB';
    public const string BRL = 'BRL';
    public const string BSD = 'BSD';
    public const string BTN = 'BTN';
    public const string BWP = 'BWP';
    public const string BYN = 'BYN';
    public const string BYR = 'BYR';
    public const string BZD = 'BZD';
    public const string CAD = 'CAD';
    public const string CDF = 'CDF';
    public const string CHF = 'CHF';
    public const string CLF = 'CLF';
    public const string CLP = 'CLP';
    public const string CNH = 'CNH';
    public const string CNY = 'CNY';
    public const string COP = 'COP';
    public const string CRC = 'CRC';
    public const string CUC = 'CUC';
    public const string CUP = 'CUP';
    public const string CVE = 'CVE';
    public const string CYP = 'CYP';
    public const string CZK = 'CZK';
    public const string DJF = 'DJF';
    public const string DKK = 'DKK';
    public const string DOP = 'DOP';
    public const string DZD = 'DZD';
    public const string EGP = 'EGP';
    public const string EEK = 'EEK';
    public const string ERN = 'ERN';
    public const string ETB = 'ETB';
    public const string EUR = 'EUR';
    public const string FJD = 'FJD';
    public const string FKP = 'FKP';
    public const string GBP = 'GBP';
    public const string GEL = 'GEL';
    public const string GGP = 'GGP';
    public const string GHS = 'GHS';
    public const string GIP = 'GIP';
    public const string GMD = 'GMD';
    public const string GNF = 'GNF';
    public const string GTQ = 'GTQ';
    public const string GYD = 'GYD';
    public const string HKD = 'HKD';
    public const string HNL = 'HNL';
    public const string HRK = 'HRK';
    public const string HTG = 'HTG';
    public const string HUF = 'HUF';
    public const string IDR = 'IDR';
    public const string ILS = 'ILS';
    public const string IMP = 'IMP';
    public const string INR = 'INR';
    public const string IQD = 'IQD';
    public const string IRR = 'IRR';
    public const string ISK = 'ISK';
    public const string JEP = 'JEP';
    public const string JMD = 'JMD';
    public const string JOD = 'JOD';
    public const string JPY = 'JPY';
    public const string KES = 'KES';
    public const string KGS = 'KGS';
    public const string KHR = 'KHR';
    public const string KMF = 'KMF';
    public const string KPW = 'KPW';
    public const string KRW = 'KRW';
    public const string KWD = 'KWD';
    public const string KYD = 'KYD';
    public const string KZT = 'KZT';
    public const string LAK = 'LAK';
    public const string LBP = 'LBP';
    public const string LD = 'LD';
    public const string LKR = 'LKR';
    public const string LRD = 'LRD';
    public const string LSL = 'LSL';
    public const string LTL = 'LTL';
    public const string LVL = 'LVL';
    public const string LYD = 'LYD';
    public const string MAD = 'MAD';
    public const string MDL = 'MDL';
    public const string MGA = 'MGA';
    public const string MKD = 'MKD';
    public const string MMK = 'MMK';
    public const string MNT = 'MNT';
    public const string MOP = 'MOP';
    public const string MRO = 'MRO';
    public const string MRU = 'MRU';
    public const string MTL = 'MTL';
    public const string MUR = 'MUR';
    public const string MVR = 'MVR';
    public const string MWK = 'MWK';
    public const string MXN = 'MXN';
    public const string MYR = 'MYR';
    public const string MZN = 'MZN';
    public const string NAD = 'NAD';
    public const string NGN = 'NGN';
    public const string NIO = 'NIO';
    public const string NOK = 'NOK';
    public const string NPR = 'NPR';
    public const string NZD = 'NZD';
    public const string OMR = 'OMR';
    public const string PAB = 'PAB';
    public const string PEN = 'PEN';
    public const string PGK = 'PGK';
    public const string PHP = 'PHP';
    public const string PKR = 'PKR';
    public const string PLN = 'PLN';
    public const string PYG = 'PYG';
    public const string QAR = 'QAR';
    public const string ROL = 'ROL';
    public const string RON = 'RON';
    public const string RSD = 'RSD';
    public const string RUB = 'RUB';
    public const string RWF = 'RWF';
    public const string SAR = 'SAR';
    public const string SBD = 'SBD';
    public const string SCR = 'SCR';
    public const string SDG = 'SDG';
    public const string SEK = 'SEK';
    public const string SGD = 'SGD';
    public const string SHP = 'SHP';
    public const string SIT = 'SIT';
    public const string SKK = 'SKK';
    public const string SLE = 'SLE';
    public const string SLL = 'SLL';
    public const string SOS = 'SOS';
    public const string SRD = 'SRD';
    public const string SSP = 'SSP';
    public const string STD = 'STD';
    public const string STN = 'STN';
    public const string SVC = 'SVC';
    public const string SYP = 'SYP';
    public const string SZL = 'SZL';
    public const string THB = 'THB';
    public const string TJS = 'TJS';
    public const string TMT = 'TMT';
    public const string TND = 'TND';
    public const string TOP = 'TOP';
    public const string TRL = 'TRL';
    public const string TRY = 'TRY';
    public const string TTD = 'TTD';
    public const string TWD = 'TWD';
    public const string TZS = 'TZS';
    public const string UAH = 'UAH';
    public const string UGX = 'UGX';
    public const string USD = 'USD';
    public const string UYU = 'UYU';
    public const string UZS = 'UZS';
    public const string VEF = 'VEF';
    public const string VEF_BLKMKT = 'VEF_BLKMKT';
    public const string VEF_DICOM = 'VEF_DICOM';
    public const string VEF_DIPRO = 'VEF_DIPRO';
    public const string VES = 'VES';
    public const string VND = 'VND';
    public const string VUV = 'VUV';
    public const string WST = 'WST';
    public const string XAF = 'XAF';
    public const string XAG = 'XAG';
    public const string XAU = 'XAU';
    public const string XCD = 'XCD';
    public const string XCG = 'XCG';
    public const string XDR = 'XDR';
    public const string XOF = 'XOF';
    public const string XPD = 'XPD';
    public const string XPF = 'XPF';
    public const string XPT = 'XPT';
    public const string YER = 'YER';
    public const string ZAR = 'ZAR';
    public const string ZMK = 'ZMK';
    public const string ZMW = 'ZMW';
    public const string ZWG = 'ZWG';
    public const string ZWL = 'ZWL';
    /**
     * 0: Symbol
     * 1: Name
     * 2: Countries (comma separated).
     *
     * @var array<string, array{0: string, 1: string, 2: string}>
     */
    public static array $list = [
        self::AED => ['د.إ', 'UAE Dirham', 'UAE'],
        self::AFN => ['؋', 'Afghan Afghani', 'Afghanistan'],
        self::ALL => ['L', 'Albanian Lek', 'Albania'],
        self::AMD => ['֏', 'Armenian Dram', 'Armenian'],
        self::ANG => ['NAƒ', 'Netherlands Antillean Guilder', 'Netherlands'],
        self::AOA => ['Kz', 'Angolan Kwanza', 'Angolan'],
        self::ARS => ['$', 'Argentine Peso', 'Argentina'],
        self::AUD => ['A$', 'Australian Dollar', 'Australia, Christmas Island, Cocos (Keeling) Islands, Heard Island and McDonald Islands, Kiribati, Nauru, Norfolk Island, Tuvalu'],
        self::AWG => ['ƒ', 'Aruban Florin', 'Aruba'],
        self::AZN => ['₼', 'Azerbaijani Manat', 'Azerbaijan'],
        self::BAM => ['KM', 'Bosnia-Herzegovina Convertible Marka', 'Bosnia'],
        self::BBD => ['Bds$', 'Barbados Dollar', 'Barbados'],
        self::BDT => ['৳', 'Bangladeshi Taka', 'Bangladeshi'],
        self::BGN => ['Лв.', 'Bulgarian Lăv', 'Bulgaria'],
        self::BHD => ['د.ب', 'Bahraini Dinar', 'Bahraini'],
        self::BIF => ['FBu', 'Burundian Franc', 'Burundian'],
        self::BMD => ['$', 'Bermudian Dollar', 'Bermuda'],
        self::BND => ['B$', 'Brunei Dollar', 'Brunei'],
        self::BOB => ['Bs', 'Boliviano', 'Bolivia'],
        self::BRL => ['R$', 'Brazilian Real', 'Brazil'],
        self::BSD => ['$', 'Bahamian Dollar', 'Bahamas'],
        self::BTN => ['Nu.', 'Bhutanese Ngultrum', 'Bhutanese'],
        self::BWP => ['P', 'Botswana Pula', 'Botswana'],
        self::BYN => ['BYN', 'Belarussian Ruble', 'Belarussian'],
        self::BYR => ['BYN', 'Belarusian Rouble', 'Belarus'],
        self::BZD => ['$', 'Belize Dollar', 'Belize'],
        self::CAD => ['CAD $', 'Canadian Dollar', 'Canada'],
        self::CDF => ['FC', 'Congolese Franc', 'Congolese'],
        self::CHF => ['Fr.', 'Swiss Franc', 'Switzerland, Liechtenstein'],
        self::CLF => ['UF', 'Chilean Unit of Account (UF)', 'Chile'],
        self::CLP => ['$', 'Chilean Peso', 'Chile'],
        self::CNH => ['¥', 'Chinese Yuan Renminbi', 'Chinese'],
        self::CNY => ['¥', 'Chinese Yuan', 'China'],
        self::COP => ['$', 'Colombian Peso', 'Colombia'],
        self::CRC => ['₡', 'Costa Rican Colon', 'Costa'],
        self::CUC => ['CUC', 'Cuban Convertible Peso', 'Cuban'],
        self::CUP => ['$', 'Cuban Peso', 'Cuba'],
        self::CVE => ['$', 'Cape Verde Escudo', 'Cape'],
        self::CYP => ['£', 'Cypriot Pound', 'Cyprus'],
        self::CZK => ['CZK', 'Czech Koruna', 'Czech'],
        self::DJF => ['Fdj', 'Djiboutian Franc', 'Djiboutian'],
        self::DKK => ['Kr.', 'Danish Krone', 'Denmark, Greenland, Faroe Islands'],
        self::DOP => ['$', 'Dominican Peso', 'Dominican'],
        self::DZD => ['دج', 'Algerian Dinar', 'Algerian'],
        self::EGP => ['E£', 'Egyptian Pound', 'Egypt'],
        self::EEK => ['kr', 'Estonian Kroon', 'Estonia'],
        self::ERN => ['نافكا', 'Eritrean Nakfa', 'Eritrean'],
        self::ETB => ['ብር', 'Ethiopian Birr', 'Ethiopian'],
        self::EUR => ['€', 'Euro', 'European Union, Italy, Belgium, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden'],
        self::FJD => ['FJ$', 'Fiji Dollar', 'Fiji'],
        self::FKP => ['£', 'Falkland Islands Pound', 'Falkland'],
        self::GBP => ['£', 'Pound Sterling', 'United Kingdom, Jersey, Guernsey, Isle of Man, Gibraltar, South Georgia and the South Sandwich Islands, British Antarctic Territory, Tristan da Cunha'],
        self::GEL => ['ლ', 'Georgian Lari', 'Georgian'],
        self::GGP => ['£', 'Guernsey Pound', 'Guernsey'],
        self::GHS => ['GH₵', 'Ghanaian Cedi', 'Ghanaian'],
        self::GIP => ['£', 'Gibraltar Pound', 'Gibraltar'],
        self::GMD => ['D', 'Gambian Dalasi', 'Gambian'],
        self::GNF => ['FG', 'Guinean Franc', 'Guinean'],
        self::GTQ => ['Q', 'Guatemalan Quetzal', 'Guatemala'],
        self::GYD => ['G$', 'Guyanese Dollar', 'Guyana'],
        self::HKD => ['HK$', 'Hong Kong Dollar', 'Hong'],
        self::HNL => ['L', 'Honduran Lempira', 'Honduras'],
        self::HRK => ['kn', 'Croatian Kuna', 'Croatia'],
        self::HTG => ['G', 'Haitian Gourde', 'Haitian'],
        self::HUF => ['Ft', 'Hungarian Forint', 'Hungary'],
        self::IDR => ['Rp', 'Indonesian Rupiah', 'Indonesia'],
        self::ILS => ['₪', 'Israeli New Sheqel', 'Israel, Palestinian territories'],
        self::IMP => ['£', 'Isle of Man Pound', 'Isle of Man'],
        self::INR => ['₹', 'Indian Rupee', 'India, Bhutan'],
        self::IQD => ['ع.د', 'Iraqi Dinar', 'Iraqi'],
        self::IRR => ['﷼', 'Iranian Rial', 'Iran'],
        self::ISK => ['kr', 'Icelandic Króna', 'Iceland'],
        self::JEP => ['£', 'Jersey Pound', 'Jersey'],
        self::JMD => ['$', 'Jamaican Dollar', 'Jamaica'],
        self::JOD => ['د.ا', 'Jordanian Dinar', 'Jordanian'],
        self::JPY => ['¥', 'Japanese Yen', 'Japan'],
        self::KES => ['Ksh', 'Kenyan Shilling', 'Kenyan'],
        self::KGS => ['Лв', 'Kyrgyzstani Som', 'Kyrgyzstan'],
        self::KHR => ['៛', 'Cambodian Riel', 'Cambodia'],
        self::KMF => ['CF', 'Comoro Franc', 'Comoro'],
        self::KPW => ['₩', 'North Korean Won', 'Korea'],
        self::KRW => ['₩', 'South Korean Won', 'Korea'],
        self::KWD => ['د.ك', 'Kuwaiti Dinar', 'Kuwaiti'],
        self::KYD => ['$', 'Cayman Islands Dollar', 'Cayman'],
        self::KZT => ['₸', 'Kazakhstani Tenge', 'Kazakhstan'],
        self::LAK => ['₭', 'Lao Kip', 'Laos'],
        self::LBP => ['ل.ل.', 'Lebanese Pound', 'Lebanon'],
        self::LD => ['L$', 'Linden Dollar', 'Second Life'],
        self::LKR => ['රු', 'Sri Lankan Rupee', 'Sri'],
        self::LRD => ['L$', 'Liberian Dollar', 'Liberia'],
        self::LSL => ['M', 'Lesotho Loti', 'Lesotho'],
        self::LTL => ['Lt', 'Lithuanian Litas', 'Lithuania'],
        self::LVL => ['Ls', 'Latvian Lats', 'Latvia'],
        self::LYD => ['ل.د', 'Libyan Dinar', 'Libyan'],
        self::MAD => ['MAD', 'Moroccan Dirham', 'Morocco, Western Sahara'],
        self::MDL => ['L', 'Moldovan Leu', 'Moldovan'],
        self::MGA => ['Ar', 'Malagasy Ariary', 'Malagasy'],
        self::MKD => ['Ден', 'Macedonian Denar', 'Macedonia'],
        self::MMK => ['K', 'Myanmar Kyat', 'Myanmar'],
        self::MNT => ['₮', 'Mongolian Tögrög', 'Mongolia'],
        self::MOP => ['MOP$', 'Macanese Pataca', 'Macanese'],
        self::MRO => ['UM', 'Mauritanian Ouguiya', 'Mauritanian'],
        self::MRU => ['UM', 'Mauritanian Ouguiya', 'Mauritania'],
        self::MTL => ['Lm', 'Maltese Lira', 'Malta'],
        self::MUR => ['₨', 'Mauritian Rupee', 'Mauritius'],
        self::MVR => ['Rf', 'Maldivian Rufiyaa', 'Maldivian'],
        self::MWK => ['MK', 'Malawian Kwacha', 'Malawian'],
        self::MXN => ['Mex$', 'Mexican Peso', 'Mexico'],
        self::MYR => ['RM', 'Malaysian Ringgit', 'Malaysia'],
        self::MZN => ['MT', 'Mozambican Metical', 'Mozambique'],
        self::NAD => ['N$', 'Namibian Dollar', 'Namibia'],
        self::NGN => ['₦', 'Nigerian Naira', 'Nigeria'],
        self::NIO => ['C$', 'Nicaraguan Córdoba', 'Nicaragua'],
        self::NOK => ['kr', 'Norwegian Krone', 'Norway, Bouvet Island, Peter I Island, Queen Maud Land'],
        self::NPR => ['रू', 'Nepalese Rupee', 'Nepal'],
        self::NZD => ['$', 'New Zealand Dollar', 'New Zealand, Cook Islands, Niue, Ross Dependency, Tokelau, Pitcairn Islands'],
        self::OMR => ['ر.ع.', 'Omani Rial', 'Oman'],
        self::PAB => ['B/.', 'Panamanian Balboa', 'Panama'],
        self::PEN => ['S/', 'Peruvian Nuevo Sol', 'Peru'],
        self::PGK => ['K', 'Papua New Guinean Kina', 'Papua'],
        self::PHP => ['₱', 'Philippine Peso', 'Philippines'],
        self::PKR => ['₨', 'Pakistani Rupee', 'Pakistan'],
        self::PLN => ['zł', 'Polish Zloty', 'Poland'],
        self::PYG => ['₲', 'Paraguayan Guarani', 'Paraguay'],
        self::QAR => ['ر.ق', 'Qatari Rial', 'Qatar'],
        self::ROL => ['lei', 'Romanian Leu (old)', 'Romania'],
        self::RON => ['lei', 'Romanian Leu', 'Romania'],
        self::RSD => ['din', 'Serbian Dinar', 'Serbia'],
        self::RUB => ['₽', 'Russian Ruble', 'Russia, Abkhazia, South Ossetia'],
        self::RWF => ['R₣', 'Rwandan Franc', 'Rwandan'],
        self::SAR => ['ر.س', 'Saudi Riyal', 'Saudi Arabia'],
        self::SBD => ['Si$', 'Solomon Islands Dollar', 'Solomon'],
        self::SCR => ['SR', 'Seychelles Rupee', 'Seychelles'],
        self::SDG => ['ج.س.', 'Sudanese Pound', 'Sudanese'],
        self::SEK => ['kr', 'Swedish Krona', 'Sweden'],
        self::SGD => ['$', 'Singapore Dollar', 'Singapore'],
        self::SHP => ['£', 'Saint Helena Pound', 'Saint'],
        self::SIT => ['SIT', 'Slovenian Tolar', 'Slovenia'],
        self::SKK => ['Sk', 'Slovak Koruna', 'Slovakia'],
        self::SLE => ['Le', 'Sierra Leonean Leone', 'Sierra Leone'],
        self::SLL => ['Le', 'Sierra Leonean Leone', 'Sierra'],
        self::SOS => ['Sh.so.', 'Somali Shilling', 'Somalia'],
        self::SRD => ['$', 'Surinamese Dollar', 'Suriname'],
        self::SSP => ['£', 'South Sudanese Pound', 'South'],
        self::STD => ['Db', 'Sao Tomean Dobra', 'Sao'],
        self::STN => ['Db', 'São Tomé and Príncipe Dobra', 'São Tomé and Príncipe'],
        self::SVC => ['₡', 'Salvadoran Colón', 'El Salvador'],
        self::SYP => ['£S', 'Syrian Pound', 'Syria'],
        self::SZL => ['E', 'Swazi Lilangeni', 'Swazi'],
        self::THB => ['฿', 'Thai Baht', 'Thailand'],
        self::TJS => ['ЅM', 'Tajikistani Somoni', 'Tajikistani'],
        self::TMT => ['T', 'Turkmenistani Manat', 'Turkmenistani'],
        self::TND => ['د.ت', 'Tunisian Dinar', 'Tunisian'],
        self::TOP => ['T$', 'Tongan paʻanga', 'Tongan'],
        self::TRL => ['TL', 'Turkish Lira (old)', 'Turkey'],
        self::TRY => ['₺', 'Turkish Lira', 'Turkey, Northern Cyprus'],
        self::TTD => ['$', 'Trinidad and Tobago Dollar', 'Trinidad'],
        self::TWD => ['$', 'New Taiwan Dollar', 'Taiwan'],
        self::TZS => ['TSh', 'Tanzanian Shilling', 'Tanzanian'],
        self::UAH => ['₴', 'Ukrainian Hryvnia', 'Ukraine'],
        self::UGX => ['USh', 'Ugandan Shilling', 'Ugandan'],
        self::USD => ['$', 'US Dollar', 'United States, Ecuador, El Salvador, Marshall Islands, Micronesia, Palau, East Timor'],
        self::UYU => ['$', 'Uruguayan Peso', 'Uruguay'],
        self::UZS => ['so\'m', 'Uzbekistan Som', 'Uzbekistan'],
        self::VEF => ['VEF', 'Venezuelan Bolivar', 'Venezuela'],
        self::VEF_BLKMKT => ['Bs', 'Venezuelan Bolivar (Black Market)', 'Venezuela'],
        self::VEF_DICOM => ['Bs', 'Venezuelan Bolivar (DICOM)', 'Venezuela'],
        self::VEF_DIPRO => ['Bs', 'Venezuelan Bolivar (DIPRO)', 'Venezuela'],
        self::VES => ['Bs.S', 'Venezuelan Sovereign Bolivar', 'Venezuela'],
        self::VND => ['₫', 'Vietnamese Dong', 'Viet'],
        self::VUV => ['VT', 'Vanuatu Vatu', 'Vanuatu'],
        self::WST => ['SAT', 'Samoan Tālā', 'Samoan'],
        self::XAF => ['FCFA', 'CFA Franc BEAC', 'Cameroon, Central African Republic, Chad, Republic of the Congo, Equatorial Guinea, Gabon'],
        self::XAG => ['oz t', 'Silver', 'Global'],
        self::XAU => ['oz t', 'Gold', 'Global'],
        self::XCD => ['$', 'East Caribbean Dollar', 'Antigua and Barbuda, Commonwealth of Dominica, Grenada, Montserrat, St. Kitts and Nevis, Saint Lucia, St. Vincent and the Grenadines'],
        self::XCG => ['ƒ', 'Caribbean Guilder', 'Curaçao, Sint Maarten'],
        self::XDR => ['SDR', 'Special Drawing Rights', 'International Monetary Fund'],
        self::XOF => ['CFA', 'CFA Franc BCEAO', 'Benin, Burkina Faso, Côte d\'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo'],
        self::XPD => ['oz t', 'Palladium', 'Global'],
        self::XPF => ['₣', 'CFP Franc', 'French Polynesia, New Caledonia, Wallis and Futuna'],
        self::XPT => ['oz t', 'Platinum', 'Global'],
        self::YER => ['﷼', 'Yemeni Rial', 'Yemen'],
        self::ZAR => ['R', 'South African Rand', 'South Africa, Lesotho, Namibia, Eswatini'],
        self::ZMK => ['ZK', 'Zambian Kwacha (old)', 'Zambia'],
        self::ZMW => ['ZK', 'Zambian Kwacha', 'Zambian'],
        self::ZWG => ['ZiG', 'Zimbabwe Gold', 'Zimbabwe'],
        self::ZWL => ['$', 'Zimbabwean Dollar', 'Zimbabwe'],
    ];
}
